(()=>{
  const SOURCE=Array.isArray(window.JR_BOX_ITEMS)?window.JR_BOX_ITEMS:[],KEY='jr_box_bom_items_v1';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const norm=v=>String(v??'').trim(),uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,6);
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY))||SOURCE}catch(_){return SOURCE}};let items=read(),selected=items[0]?.id,editing=-1;
  const save=()=>localStorage.setItem(KEY,JSON.stringify(items));
  const style=document.createElement('style');style.textContent=`
    .box-toolbar{display:grid;grid-template-columns:2fr 1fr 1fr auto;gap:10px;padding:15px;margin-bottom:16px}.box-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(230px,1fr));gap:12px}.box-card{border:1px solid #dbe3ee;border-radius:12px;background:#fff;overflow:hidden;cursor:pointer;transition:.15s}.box-card:hover{transform:translateY(-2px);box-shadow:0 8px 22px rgba(15,23,42,.12)}.box-card.active{outline:3px solid #2563eb}.box-img{width:100%;height:145px;object-fit:contain;background:#f8fafc}.box-info{padding:11px}.box-info strong{display:block;color:#075092}.box-info small{display:block;color:#64748b;margin-top:3px}.box-flow{padding:18px;margin-bottom:16px}.box-flow-head{display:flex;justify-content:space-between;gap:10px;align-items:start}.box-part-summary{display:grid;grid-template-columns:150px 1fr;gap:14px;align-items:center;margin:15px 0}.box-main-img{width:150px;height:115px;object-fit:contain;background:#f8fafc;border-radius:10px}.box-process-flow{display:flex;align-items:center;gap:8px;overflow:auto;padding:15px 4px}.box-node{min-width:135px;padding:13px 10px;border:2px solid #f97316;border-radius:9px;background:#fff7ed;color:#9a3412;text-align:center;font-weight:900}.box-node.start,.box-node.finish{border-color:#075aa5;background:#eff6ff;color:#075aa5}.box-arrow{font-size:26px;color:#2563eb;font-weight:950}.box-detail-table{width:100%;border-collapse:collapse}.box-detail-table th,.box-detail-table td{padding:8px;border:1px solid #e2e8f0;text-align:left;font-size:11px}.box-editor{padding:18px;margin-bottom:16px}.box-editor[hidden]{display:none}.box-form{display:grid;grid-template-columns:repeat(3,minmax(170px,1fr));gap:10px}.box-process-inputs{grid-column:1/-1;display:grid;grid-template-columns:repeat(4,minmax(140px,1fr));gap:8px;padding:12px;border:1px solid #dbe3ee;border-radius:10px}.box-actions{display:flex;gap:7px;flex-wrap:wrap}.box-count{font-weight:850;color:#475569}@media(max-width:800px){.box-toolbar,.box-form{grid-template-columns:1fr 1fr}.box-process-inputs{grid-template-columns:1fr 1fr}}@media(max-width:520px){.box-toolbar,.box-form,.box-process-inputs,.box-part-summary{grid-template-columns:1fr}}
  `;document.head.appendChild(style);
  const nav=document.querySelector('.nav');let btn=document.querySelector('[data-view="boxbom"]');if(!btn){btn=document.createElement('button');btn.className='nav-item';btn.dataset.view='boxbom';btn.textContent='BOM Box';nav?.insertBefore(btn,nav.querySelector('[data-view="settings"]'))}
  const view=document.createElement('section');view.className='view';view.id='view-boxbom';view.innerHTML=`
    <div class="box-toolbar card"><div class="field"><label>ค้นหา Part No. / Part Name</label><input id="boxSearch" type="search" placeholder="พิมพ์คำค้นหา"></div><div class="field"><label>Model</label><select id="boxModel"><option value="">ทุก Model</option></select></div><div class="field"><label>Process</label><select id="boxProcess"><option value="">ทุก Process</option></select></div><div class="field"><label>&nbsp;</label><button class="btn primary" id="boxAdd">+ เพิ่ม Part Box</button></div></div>
    <article class="card box-editor" id="boxEditor" hidden><div class="panel-head"><div><h2 id="boxEditorTitle">เพิ่ม Part Box</h2><p>เลือก Process จาก Dropdown ตามลำดับ Step</p></div><button class="btn ghost" id="boxClose">ปิด</button></div><form id="boxForm" class="box-form"><div class="field"><label>Part No. *</label><input id="boxPartNo" required></div><div class="field"><label>Part Name *</label><input id="boxPartName" required></div><div class="field"><label>Model</label><input id="boxEditModel"></div><div class="field"><label>Spec / Size</label><input id="boxSpec"></div><div class="field"><label>Tooling No.</label><input id="boxTooling"></div><div class="field"><label>Machine No.</label><input id="boxMachine"></div><div class="box-process-inputs">${Array.from({length:7},(_,i)=>`<div class="field"><label>Step ${i+1}</label><select id="boxStep${i+1}"><option value="">-- ไม่มี --</option><option>STAMPING</option><option>BENDING</option><option>SPOT WELDING</option><option>ROBOT WELDING</option><option>CO2 WELDING</option><option>RIVETING</option><option>TAPPING</option><option>ASSEMBLY</option><option>SORTING</option><option>PACKING</option></select></div>`).join('')}</div><div class="box-actions"><button class="btn primary" type="submit">บันทึก</button><button class="btn ghost" type="button" id="boxCancel">ยกเลิก</button></div></form></article>
    <article class="card box-flow" id="boxFlow"></article><div class="panel-head"><div><h2>รายการ Box ทั้งหมด</h2><p class="box-count" id="boxCount"></p></div></div><div class="box-grid" id="boxGrid"></div>`;document.querySelector('.main')?.appendChild(view);
  const $=id=>document.getElementById(id),KNOWN=['Stamping','Bending','Spot Welding','Robot Welding','Co2 Welding','Riveting','Tapping','Assembly','Sorting','Packing'];
  const processList=item=>{if(Array.isArray(item.processes))return item.processes.filter(Boolean);const raw=norm(item.process).toLowerCase(),out=[];KNOWN.forEach(p=>{if(raw.includes(p.toLowerCase()))out.push(p.toUpperCase())});if(!out.length&&raw)out.push(norm(item.process).toUpperCase());const n=Math.max(0,Number(item.steps)||0);while(out.length<n)out.splice(Math.max(1,out.length),0,'STAMPING');return out.slice(0,n||out.length)};
  const rebuildFilters=()=>{const models=[...new Set(items.map(x=>x.model).filter(Boolean))].sort(),procs=[...new Set(items.flatMap(processList))].sort(),oldM=$('boxModel').value,oldP=$('boxProcess').value;$('boxModel').innerHTML='<option value="">ทุก Model</option>'+models.map(x=>`<option>${esc(x)}</option>`).join('');$('boxProcess').innerHTML='<option value="">ทุก Process</option>'+procs.map(x=>`<option>${esc(x)}</option>`).join('');$('boxModel').value=oldM;$('boxProcess').value=oldP};
  const renderFlow=()=>{const x=items.find(v=>v.id===selected)||items[0];if(!x){$('boxFlow').innerHTML='<div class="empty">ยังไม่มีข้อมูล</div>';return}const ps=processList(x),img=x.image||'';$('boxFlow').innerHTML=`<div class="box-flow-head"><div><h2>${esc(x.partNo)} — ${esc(x.partName)}</h2><p>${esc(x.model||'ไม่ระบุ Model')}</p></div><div class="box-actions"><button class="btn ghost" data-box-edit="${esc(x.id)}">แก้ไข</button><button class="btn ghost" data-box-delete="${esc(x.id)}">ลบ</button></div></div><div class="box-part-summary">${img?`<img class="box-main-img" src="${img}">`:'<div class="box-main-img"></div>'}<div><strong>Spec:</strong> ${esc(x.spec||'-')}<br><strong>Tooling:</strong> ${esc(x.tooling||'-')}<br><strong>Machine:</strong> ${esc(x.machine||'-')}<br><strong>Total:</strong> ${ps.length} Step</div></div><div class="box-process-flow"><div class="box-node start">RAW MATERIAL</div>${ps.map((p,i)=>`<div class="box-arrow">→</div><div class="box-node">STEP ${i+1}<br>${esc(p)}</div>`).join('')}<div class="box-arrow">→</div><div class="box-node finish">${esc(x.partNo)}<br>FINISHED PART</div></div><table class="box-detail-table"><tr><th>Part No.</th><th>Part Name</th><th>Model</th><th>Spec/Size</th><th>Tooling</th><th>Machine</th></tr><tr><td>${esc(x.partNo)}</td><td>${esc(x.partName)}</td><td>${esc(x.model||'-')}</td><td>${esc(x.spec||'-')}</td><td>${esc(x.tooling||'-')}</td><td>${esc(x.machine||'-')}</td></tr></table>`};
  const render=()=>{const q=norm($('boxSearch').value).toLowerCase(),m=$('boxModel').value,p=$('boxProcess').value,filtered=items.filter(x=>(!q||`${x.partNo} ${x.partName} ${x.model}`.toLowerCase().includes(q))&&(!m||x.model===m)&&(!p||processList(x).includes(p)));$('boxCount').textContent=`${filtered.length} รายการ`;$('boxGrid').innerHTML=filtered.map(x=>`<article class="box-card ${x.id===selected?'active':''}" data-box-id="${esc(x.id)}">${x.image?`<img class="box-img" src="${x.image}" loading="lazy">`:'<div class="box-img"></div>'}<div class="box-info"><strong>${esc(x.partNo)}</strong><small>${esc(x.partName)}</small><small>${esc(x.model||'ไม่ระบุ Model')} · ${processList(x).length} Step</small></div></article>`).join('');renderFlow()};
  const openEditor=id=>{editing=id?items.findIndex(x=>x.id===id):-1;const x=editing>=0?items[editing]:{};$('boxForm').reset();$('boxEditorTitle').textContent=editing>=0?'แก้ไข '+x.partNo:'เพิ่ม Part Box';$('boxPartNo').value=x.partNo||'';$('boxPartName').value=x.partName||'';$('boxEditModel').value=x.model||'';$('boxSpec').value=x.spec||'';$('boxTooling').value=x.tooling||'';$('boxMachine').value=x.machine||'';const ps=processList(x);Array.from({length:7},(_,i)=>$('boxStep'+(i+1)).value=ps[i]||'');$('boxEditor').hidden=false;$('boxEditor').scrollIntoView({behavior:'smooth'})};
  $('boxForm').onsubmit=e=>{e.preventDefault();const old=editing>=0?items[editing]:{},x={...old,id:old.id||uid(),partNo:norm($('boxPartNo').value),partName:norm($('boxPartName').value),model:norm($('boxEditModel').value),spec:norm($('boxSpec').value),tooling:norm($('boxTooling').value),machine:norm($('boxMachine').value),processes:Array.from({length:7},(_,i)=>$('boxStep'+(i+1)).value).filter(Boolean)};if(editing>=0)items[editing]=x;else items.push(x);selected=x.id;save();rebuildFilters();render();$('boxEditor').hidden=true;showToast('บันทึก BOM Box แล้ว')};
  $('boxSearch').oninput=render;$('boxModel').onchange=render;$('boxProcess').onchange=render;$('boxAdd').onclick=()=>openEditor();$('boxClose').onclick=$('boxCancel').onclick=()=>$('boxEditor').hidden=true;$('boxGrid').onclick=e=>{const c=e.target.closest('[data-box-id]');if(c){selected=c.dataset.boxId;render()}};$('boxFlow').onclick=e=>{const ed=e.target.closest('[data-box-edit]');if(ed)return openEditor(ed.dataset.boxEdit);const del=e.target.closest('[data-box-delete]');if(del&&confirm('ลบ Part นี้หรือไม่?')){items=items.filter(x=>x.id!==del.dataset.boxDelete);selected=items[0]?.id;save();rebuildFilters();render()}};
  btn.addEventListener('click',()=>{if(typeof showView==='function')showView('boxbom');document.getElementById('pageTitle').textContent='BOM Box'});rebuildFilters();render();
})();
