(()=>{
const API='https://script.google.com/macros/s/AKfycbzrNCLwRIt71fF6KiKnBltlc7dXvmJkwvRZKi7QILFAbrCYqaGMzQ_L9FryUkKRYDgT/exec';
const pfmt=new Intl.NumberFormat('en-US',{maximumFractionDigits:3});
const pEsc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const pNum=v=>{const n=Number(String(v??'').replace(/,/g,'').replace(/%/g,'').trim());return Number.isFinite(n)?n:0};
const pNorm=v=>String(v??'').trim();
let planRows=[];

const style=document.createElement('style');style.textContent=`
.planning-filter{margin-bottom:16px;padding:14px 16px;background:#fff;border:1px solid #e5eaf2;border-radius:14px;display:grid;grid-template-columns:minmax(260px,440px);gap:6px}.planning-filter label{font-size:12px;font-weight:800;color:#475569}.planning-filter select{padding:11px 12px;border:1px solid #d9e0ea;border-radius:9px;background:#fff;font-weight:800}.planning-controls{display:grid;grid-template-columns:repeat(2,minmax(260px,1fr));gap:16px;margin-bottom:18px}.planning-control{padding:18px;background:linear-gradient(135deg,#142f4b,#193b5d);border-radius:16px;color:#fff}.planning-control label{display:block;font-size:13px;font-weight:800;margin-bottom:10px}.planning-control-row{display:grid;grid-template-columns:90px 1fr;gap:14px;align-items:center}.planning-control input[type=number]{width:100%;padding:10px;border:0;border-radius:9px;text-align:center;font-weight:800}.planning-control input[type=range]{width:100%;accent-color:#f59e0b}.planning-control small{display:block;margin-top:8px;color:#cbd5e1}.planning-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:18px}.planning-kpi{padding:17px;border-radius:14px;background:#fff;border:1px solid #e5eaf2}.planning-kpi span{font-size:11px;color:#6d7890;font-weight:750}.planning-kpi strong{display:block;margin-top:6px;font-size:25px}.planning-table th,.planning-table td{text-align:center!important;vertical-align:middle}.planning-table thead th{background:#1e3a5f!important;color:#fff!important}.planning-group td{background:#eef4ff!important;color:#1e3a5f!important;font-weight:900!important;text-align:left!important}.planning-bottleneck td{background:#fff7ed!important}.planning-bottleneck td:last-child{color:#dc2626!important;font-weight:900}.planning-table td:last-child{font-weight:900;color:#16a34a}.planning-badge{padding:5px 9px;border-radius:999px;font-size:11px;font-weight:850;background:#ecfdf3;color:#166534}.planning-status{font-size:11px;color:#64748b;margin-top:5px}@media(max-width:900px){.planning-controls{grid-template-columns:1fr}.planning-kpis{grid-template-columns:repeat(2,1fr)}}`;document.head.appendChild(style);

function navToPlanning(){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view==='planning'));document.getElementById('view-planning')?.classList.add('active');const t=document.getElementById('pageTitle');if(t)t.textContent='Planning Capacity';document.getElementById('sidebar')?.classList.remove('open')}
const nav=document.querySelector('.nav');if(nav&&!document.querySelector('[data-view="planning"]')){const b=document.createElement('button');b.className='nav-item';b.dataset.view='planning';b.textContent='Planning Capacity';nav.insertBefore(b,nav.querySelector('[data-view="settings"]'));b.addEventListener('click',navToPlanning)}
const main=document.querySelector('.main');if(main&&!document.getElementById('view-planning')){const v=document.createElement('section');v.className='view';v.id='view-planning';v.innerHTML=`<div class="planning-filter"><label>Final Part</label><select id="planFinalPart"><option value="">กำลังโหลด Final Part...</option></select><div id="planLoadStatus" class="planning-status">Loading from Google Sheet...</div></div><div class="planning-controls"><div class="planning-control"><label>Capacity / Efficiency (%)</label><div class="planning-control-row"><input id="planCapacityNumber" type="number" min="50" max="120" value="90"><input id="planCapacityRange" type="range" min="50" max="120" value="90"></div><small>ปรับ % กำลังการผลิตสำหรับการจำลอง</small></div><div class="planning-control"><label>ชั่วโมงทำงาน / Work Hours</label><div class="planning-control-row"><input id="planHoursNumber" type="number" min="1" max="24" step="0.5" value="10.5"><input id="planHoursRange" type="range" min="1" max="24" step="0.5" value="10.5"></div><small>กำหนดชั่วโมงผลิตจริงที่ Planning ต้องการตรวจสอบ</small></div></div><div class="planning-kpis"><div class="planning-kpi"><span>Efficiency</span><strong id="planKpiEfficiency">90%</strong></div><div class="planning-kpi"><span>Work Hours</span><strong id="planKpiHours">10.5 hr</strong></div><div class="planning-kpi"><span>Selected Final Part</span><strong id="planKpiParts">-</strong></div><div class="planning-kpi"><span>Bottleneck Output</span><strong id="planKpiOutput">0 pcs</strong></div></div><article class="card panel"><div class="panel-head"><div><h2>Planning Capacity Check by Step</h2><p>เลือก Final Part แล้วแสดงเฉพาะ Part No. / Step / Process / M/C ของ Part นั้น</p></div><span class="planning-badge">Live Simulation</span></div><div class="table-wrap"><table class="planning-table"><thead><tr><th>Final Part</th><th>Part No.</th><th>Step</th><th>Process</th><th>M/C</th><th>CT 100%<br><small>sec/pcs</small></th><th>Efficiency</th><th>Adjusted CT<br><small>sec/pcs</small></th><th>Capacity<br><small>pcs/hour</small></th><th>Work Hours</th><th>Planned Capacity<br><small>pcs</small></th></tr></thead><tbody id="planningBody"><tr><td colspan="11" class="empty">กำลังโหลดข้อมูล...</td></tr></tbody></table></div></article>`;main.appendChild(v)}

const fp=document.getElementById('planFinalPart'),cn=document.getElementById('planCapacityNumber'),cr=document.getElementById('planCapacityRange'),hn=document.getElementById('planHoursNumber'),hr=document.getElementById('planHoursRange'),status=document.getElementById('planLoadStatus');
function clamp(v,a,b){return Math.min(b,Math.max(a,Number(v)||a))}
function field(obj,names){const entries=Object.entries(obj||{}),wanted=names.map(x=>x.toLowerCase().replace(/\s+/g,' ').trim());for(const[k,v]of entries){if(wanted.includes(String(k).toLowerCase().replace(/\s+/g,' ').trim()))return v}return''}
function canon(r){const finalPart=pNorm(field(r,['Final Part','FINAL PART','FinalPart','Final part'])),partNo=pNorm(field(r,['Part No.','Part No','PART NO','PartNo'])),process=pNorm(field(r,['Process','PROCESS'])),machine=pNorm(field(r,['M/C','MC','Machine','MACHINE','M/C No.','M/C No'])),step=pNorm(field(r,['Step','STEP','Step/Qty']));let ct=0;const sec=pNum(field(r,['CT 100%','CT 100','ct 100%','ct100','ct (sec/pcs)','ct sec/pcs','sec/pcs'])),cap=pNum(field(r,['Cap 100%','Cap 100','capacity 100%','cap100','cap 100% (pcs/hour)','100%','100'])),speed=pNum(field(r,['Speed pcs/min','Speed (pcs/min)','speed pcs/min','pcs/min'])),minpcs=pNum(field(r,['speed 1 min./pcs','speed 1 min/pcs','1 min/pcs','ct (min/pcs)','ct min/pcs','production time (minutes)','生产工时（分钟）']));if(sec>0)ct=sec;else if(cap>0)ct=3600/cap;else if(speed>0)ct=60/speed;else if(minpcs>0)ct=minpcs*60;return{finalPart,partNo,process,machine,step,ct100:ct}}
function fillParts(){const parts=[...new Set(planRows.map(r=>r.finalPart).filter(Boolean))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));fp.innerHTML=parts.length?parts.map(x=>`<option value="${pEsc(x)}">${pEsc(x)}</option>`).join(''):'<option value="">No Final Part found</option>';if(parts.length&&!fp.value)fp.value=parts[0];if(status)status.textContent=parts.length?`พบ ${parts.length} Final Part จาก Google Sheet`:'ไม่พบ Final Part ในข้อมูล';render()}
function render(){const body=document.getElementById('planningBody');if(!body)return;const selected=fp.value,eff=clamp(cn.value,50,120)/100,hours=clamp(hn.value,1,24),rows=planRows.filter(r=>r.finalPart===selected&&r.ct100>0);let html='',bottleneck=0;if(rows.length){const calc=rows.map(r=>{const adj=r.ct100/eff,ph=3600/adj,out=ph*hours;return{...r,adj,ph,out}});bottleneck=Math.min(...calc.map(x=>x.out));html=`<tr class="planning-group"><td colspan="11">${pEsc(selected)} · Bottleneck Capacity = ${pfmt.format(Math.floor(bottleneck))} pcs / ${hours} hr</td></tr>`;calc.sort((a,b)=>String(a.step).localeCompare(String(b.step),undefined,{numeric:true})).forEach(r=>{const bott=Math.abs(r.out-bottleneck)<.0001;html+=`<tr class="${bott?'planning-bottleneck':''}"><td><strong>${pEsc(selected)}</strong></td><td>${pEsc(r.partNo)}</td><td><strong>${pEsc(r.step||'-')}</strong></td><td>${pEsc(r.process)}</td><td>${pEsc(r.machine)}</td><td>${pfmt.format(r.ct100)}</td><td>${(eff*100).toFixed(0)}%</td><td>${pfmt.format(r.adj)}</td><td>${pfmt.format(r.ph)}</td><td>${hours}</td><td>${pfmt.format(Math.floor(r.out))}${bott?' ⚠':''}</td></tr>`})}body.innerHTML=html||'<tr><td colspan="11" class="empty">ไม่พบข้อมูลของ Final Part นี้</td></tr>';document.getElementById('planKpiEfficiency').textContent=`${(eff*100).toFixed(0)}%`;document.getElementById('planKpiHours').textContent=`${hours} hr`;document.getElementById('planKpiParts').textContent=selected||'-';document.getElementById('planKpiOutput').textContent=`${pfmt.format(Math.floor(bottleneck))} pcs`}
function sync(a,b,min,max){const v=clamp(a.value,min,max);a.value=v;b.value=v;render()}
cn.addEventListener('input',()=>sync(cn,cr,50,120));cr.addEventListener('input',()=>sync(cr,cn,50,120));hn.addEventListener('input',()=>sync(hn,hr,1,24));hr.addEventListener('input',()=>sync(hr,hn,1,24));fp.addEventListener('change',render);
async function load(){try{if(status)status.textContent='กำลังโหลด Final Part จาก Google Sheet...';const res=await fetch(`${API}?action=capacity&t=${Date.now()}`,{cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);const data=await res.json();const raw=Array.isArray(data)?data:(data.rows||data.data||[]);planRows=raw.map(canon).filter(r=>r.finalPart);fillParts()}catch(err){fp.innerHTML='<option value="">Load failed</option>';if(status)status.textContent=`โหลดไม่สำเร็จ: ${err.message}`;document.getElementById('planningBody').innerHTML='<tr><td colspan="11" class="empty">โหลดข้อมูล Planning ไม่สำเร็จ</td></tr>'}}
load();
})();